services:
  postgres:
    image: postgres
    container_name: gonscheg-postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: Gonscheg
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - gonscheg-network

  app:
    build:
      context: .
      dockerfile: Gonscheg/Dockerfile
    image: sleepyf0x/gonscheg:latest
    container_name: gonscheg-bot
    depends_on:
      - postgres
    networks:
      - gonscheg-network
    environment:
      DB_USER: admin
      DB_PASS: admin
      DB_HOST: postgres
      TELEGRAM_BOT_TOKEN: 7813333407:AAEriK45LvvXrKhQc20YDRkNCfZ58nkrvtg
      WEATHER_API_KEY: 320057c5e1d74e4d81a105418252407

volumes:
  postgres_data:

networks:
  gonscheg-network:
    driver: bridge